### ISSUE TITLE
ImportError: No module named gmusicapi

### ISSUE THREAD

**Issue by marianolatorre** [soulfx/gmusic-playlist#22]
Hi, I just finished installing the gmusic dependency but still I can't manage to run Import.

```
pip install gmusicapi
Requirement already satisfied (use --upgrade to upgrade): gmusicapi in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): validictory!=0.9.2,>=0.8.0 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.3.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.18 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): requests!=1.2.0,!=2.2.1,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil!=2.0,>=1.3 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): proboscis>=1.2.5.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): oauth2client>=1.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): mock>=0.7.0 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.0.3 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from protobuf>=2.4.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from python-dateutil!=2.0,>=1.3->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): httplib2>=0.9.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.4 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from mock>=0.7.0->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gpsoauth==0.0.3->gmusicapi)
```

And then when I try to run it:
```
python ImportList.py ../spotify-export/amazingsongs2.txt 
Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/Users/marianolatorre/gmusic-playlist/common.py", line 5, in <module>
    from gmusicapi import Mobileclient
ImportError: No module named gmusicapi
```

```
python 
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

Thanks!

**Comment by marianolatorre** [comment]
oops I just realised that pip is using python 3.4 and the default python is 2.75...anyway I tried again with this but still can't  get it working :/

/usr/local/bin/python3.4 ImportList.py ../spotify-export/amazingsongs2.txt

**Comment by marianolatorre** [comment]
also tried : 

pip2.7 install gmusicapi
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): gmusicapi in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): validictory!=0.9.2,>=0.8.0 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.3.1 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.18 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=2.4.1 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): requests!=1.2.0,!=2.2.1,>=1.1.0 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil!=2.0,>=1.3 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): proboscis>=1.2.5.1 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): oauth2client>=1.1 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): mock>=0.7.0 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.1.0 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.0.3 in /usr/local/lib/python2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg (from protobuf>=2.4.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil!=2.0,>=1.3->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): httplib2>=0.9.1 in /usr/local/lib/python2.7/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.4 in /usr/local/lib/python2.7/site-packages (from oauth2client>=1.1->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /usr/local/lib/python2.7/site-packages (from mock>=0.7.0->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /usr/local/lib/python2.7/site-packages (from mock>=0.7.0->gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/local/lib/python2.7/site-packages (from gpsoauth==0.0.3->gmusicapi)

/usr/bin/python2.7 ImportList.py ../spotify-export/amazingsongs2.txt

Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/Users/marianolatorre/gmusic-playlist/common.py", line 5, in <module>
    from gmusicapi import Mobileclient
ImportError: No module named gmusicapi

**Comment by soulfx** [comment]
I install gmusicapi by downloading the latest source and doing &#39;python setup.py install&#39;.
