### ISSUE TITLE
404 Client Error: Not Found

### ISSUE THREAD

**Issue by adamdullenty** [soulfx/gmusic-playlist#26]
Hi,

Just trying to get some music imported and I am getting the following issue:

```
Traceback (most recent call last):
  File "ImportList.py", line 194, in <module>
    api = open_api()
  File "/home/squawk/gmusic-playlist-master/common.py", line 151, in open_api
    dlog(u'Available track details: '+str(get_google_track_details()))
  File "/home/squawk/gmusic-playlist-master/common.py", line 63, in get_google_track_details
    results = api.search_all_access(sample_song,max_results=1).get('song_hits')
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-7.0.1.dev0-py2.7.egg/gmusicapi/clients/mobileclient.py", line 940, in search_all_access
    res = self._make_call(mobileclient.Search, query, max_results)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-7.0.1.dev0-py2.7.egg/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-7.0.1.dev0-py2.7.egg/gmusicapi/protocol/shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: Search: 404 Client Error: Not Found for url: https://mclients.googleapis.com/sj/v1.11/query?q=one+u2&max-results=1
(requests kwargs: {'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': 'one u2', 'max-results': 1}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "notFound",\n    "message": "Not Found"\n   }\n  ],\n  "code": 404,\n  "message": "Not Found"\n }\n}\n')
```

**Comment by soulfx** [comment]
do you have an all access google music account?

**Comment by soulfx** [comment]
I've updated to the latest development version of gmusicapi, but I'm not able to reproduce the issue on my side.

I've added the version to the readme for the last gmusicapi version for which these playlist scripts were updated with.  Maybe give that version a try.

Someone from gmusicapi may be able to help out more.
