### ISSUE TITLE
ImportError: No module named decorator

### ISSUE THREAD

**Issue by toujames** [soulfx/gmusic-playlist#32]
tried to run ImportedList.py and get this:

```
Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/Users/toujames/Downloads/gmusic-playlist-master/common.py", line 5, in <module>
    from gmusicapi import Mobileclient
  File "/Library/Python/2.7/site-packages/gmusicapi-7.0.1_dev-py2.7.egg/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/Library/Python/2.7/site-packages/gmusicapi-7.0.1_dev-py2.7.egg/gmusicapi/clients/__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/Library/Python/2.7/site-packages/gmusicapi-7.0.1_dev-py2.7.egg/gmusicapi/clients/webclient.py", line 7, in <module>
    from gmusicapi.clients.shared import _Base
  File "/Library/Python/2.7/site-packages/gmusicapi-7.0.1_dev-py2.7.egg/gmusicapi/clients/shared.py", line 4, in <module>
    from gmusicapi.utils import utils
  File "/Library/Python/2.7/site-packages/gmusicapi-7.0.1_dev-py2.7.egg/gmusicapi/utils/utils.py", line 20, in <module>
    from decorator import decorator
ImportError: No module named decorator
```

**Comment by soulfx** [comment]
Try installing decorator with pip

https://pypi.python.org/pypi/decorator

**Comment by awadsb1** [comment]
Any answer?  I have this same issue with "import utils" and decorator

**Comment by awadsb1** [comment]
I needed to install pip for python 2.7 (I only had python 3.5).  Worked after that.
