### ISSUE TITLE
Running ImportList.py gives me an error

### ISSUE THREAD

**Issue by ghost** [soulfx/gmusic-playlist#34]
When running ImportList.py I get the following error. Any suggestions?

Login Successful.
Loading personal library... Traceback (most recent call last):
  File "ImportList.py", line 194, in <module>
    library = load_personal_library()
  File "/Users/basis/Downloads/gmusic-playlist-master/common.py", line 33, in load_personal_library
    plib = api.get_all_songs()
  File "/Library/Python/2.7/site-packages/gmusicapi/clients/mobileclient.py", line 133, in get_all_songs
    tracks = self._get_all_items(mobileclient.ListTracks, incremental, include_deleted)
  File "/Library/Python/2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1044, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "/Library/Python/2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1057, in _get_all_items_incremental
    **kwargs)
  File "/Library/Python/2.7/site-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/Library/Python/2.7/site-packages/gmusicapi/session.py", line 86, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/Library/Python/2.7/site-packages/gmusicapi/session.py", line 195, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 292, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 234, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/util.py", line 256, in is_connection_dropped
    return select([sock], [], [], 0.0)[0]
TypeError: argument must be an int, or have a fileno() method.

**Comment by soulfx** [comment]
I believe I was getting a similar error at some point on my box.  I think it had something to do with the connection to the server not being right Even though the call to login succeeded. It could have also been due to the urllib being odd in my install. Check that you have created an app specific password if you use two factor authentication.

**Comment by soulfx** [comment]
as an alternative there is now a javascript based version you can try: https://github.com/soulfx/gmusic-playlist.js

**Comment by geomybasis** [comment]
Thanks! I didn't setup 2 factor authorization and thought just entering my password would be sufficient. Your help is greatly appreciated!

**Comment by soulfx** [comment]
glad you got it working :+1:
