### ISSUE TITLE
Error with python 2.7.11?

### ISSUE THREAD

**Issue by skybondsor** [soulfx/gmusic-playlist#36]
Here's what I'm getting when I try to run ImportList.py:

```
$ python ImportList.py playlist_copy.csv
Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/Users/jordynbonds/Downloads/gmusic-playlist-master/common.py", line 5, in <module>
    from gmusicapi import Mobileclient
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.0.dev0-py2.7.egg/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.0.dev0-py2.7.egg/gmusicapi/clients/__init__.py", line 1, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.0.dev0-py2.7.egg/gmusicapi/clients/webclient.py", line 6, in <module>
    from gmusicapi.clients.shared import _Base
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.0.dev0-py2.7.egg/gmusicapi/clients/shared.py", line 3, in <module>
    from gmusicapi.utils import utils
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.0.dev0-py2.7.egg/gmusicapi/utils/utils.py", line 19, in <module>
    from google.protobuf.descriptor import FieldDescriptor
  File "/usr/local/lib/python2.7/site-packages/protobuf-3.0.0b1.post2-py2.7.egg/google/__init__.py", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

Thanks for your help!

**Comment by skybondsor** [comment]
This does seem to be specific to 2.7.11! I uninstalled that version and then installed 2.7.10 and the script is working now (though it is rejecting my password, but that's a separate issue).

For anyone encountering the same problem, I found the earlier version of Python here:
https://www.python.org/downloads/release/python-2710/

**Comment by soulfx** [comment]
I'm glad you figured it out.  That was an error I hadn't seen before. From the trace it does seem like it was jumping between two different python installs.  It was using the system python and then it jumped to one in cellar

**Comment by saurabh-promobitech** [comment]
I am facing this issue in 2.7.10 version also
