### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by goodepic** [soulfx/gmusic-playlist#39]
I got all my Spotify playlists into a nice CSV and was trying to loop through them and import them into Play Music.  I get the following error:

Reading playlist... done. 5 lines loaded.
Logging into google music...
*********@gmail.com's password: 
Traceback (most recent call last):
  File "/Users/****/Downloads/gmusic-playlist-master/ImportList.py", line 193, in <module>
    api = open_api()
  File "/Users/****/Downloads/gmusic-playlist-master/common.py", line 162, in open_api
    if not api.login(username, password, Mobileclient.FROM_MAC_ADDRESS):
  File "/usr/local/anaconda/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 64, in login
    if not self.session.login(email, password, android_id):
  File "/usr/local/anaconda/lib/python2.7/site-packages/gmusicapi/session.py", line 170, in login
    res = gpsoauth.perform_master_login(email, password, android_id)
  File "/usr/local/anaconda/lib/python2.7/site-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/anaconda/lib/python2.7/site-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/anaconda/lib/python2.7/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Any ideas why my SSL library isn't working?  I updated pyOpenSSL...

**Comment by soulfx** [comment]
The issue you are seeing may be related to https://github.com/simon-weber/gmusicapi/issues/350.  I'm guessing that the root certificates in your python install are either not being found or are out of date.  The certificates are usually a separate package.

**Comment by goodepic** [comment]
Thanks for your help.  Not quite sure still how to fix the problem.  Is it stemming from my having installed Anaconda?  I've put the anaconda dir early in my PATH, so a simple 'python' call gets that one, and my pip installer installs in the anaconda directory as well.

I also ran into a problem installing setuptools.  I worked around it after some googling by using the --ignore-installed option.  Is that causing problems?

Generally, I'm not sure how to proceed given the comments in the issue you noted above.  I have an up to date installation of certifi (that I installed yesterday in trying to get this package to work), and that pip installer installed with anaconda.  Any pointers?

Thanks!

**Comment by goodepic** [comment]
Well I don't understand exactly what the issue was with what I had installed before, but I just set up a simple virtualenv, reinstalled gmusicapi with pip, and then reran the ImportList.py file with the song list files I'd pulled down from Spotify, and things are working fine!

Thanks for providing this code!

**Comment by soulfx** [comment]
I'm glad you got it working and found it helpful.  Python can be tricky to get setup, it's one of the reasons I wrote a [JavaScript version](https://github.com/soulfx/gmusic-playlist.js).
