### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by Glecun** [soulfx/gmusic-playlist#43]
Hi,

When I execute the script, I enter my password and then I've got an SSl error:

`python ExportLists.py playlists`

> Logging into google music...
gregoire.lecun@gmail.com's password:
Traceback (most recent call last):
  File "ExportLists.py", line 17, in <module>
    api = open_api()
  File "/home/vmadmin/dev/gmusic-playlist-master/gmusic-playlist-master/common.py", line 162, in open_api
    if not api.login(username, password, Mobileclient.FROM_MAC_ADDRESS):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-7.0.0.dev0-py2.7.egg/gmusicapi/clients/mobileclient.py", line 64, in login
    if not self.session.login(email, password, android_id):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-7.0.0.dev0-py2.7.egg/gmusicapi/session.py", line 170, in login
    res = gpsoauth.perform_master_login(email, password, android_id)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth-0.0.4-py2.7.egg/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth-0.0.4-py2.7.egg/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

**Comment by soulfx** [comment]
make sure your python certificates are up to date and haven't been overriden up by other installs.  http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error

python is an annoying beast to try and setup.  there is a javascript version of this script you can also try.

**Comment by Glecun** [comment]
Thank you.

I totally agree with you, I will try this. You save me thanks ;)
