### ISSUE TITLE
No module named google.protobuf.descriptor

### ISSUE THREAD

**Issue by Flavien06** [soulfx/gmusic-playlist#44]
Hi, when i run ExportLists.py, I have this error

```
# python ImportList.py Playlist.csv

Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/volume1/public/gmusic-playlist/common.py", line 5, in <module>
    from gmusicapi import Mobileclient
  File "/volume1/public/gmusic-playlist/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/volume1/public/gmusic-playlist/gmusicapi/clients/__init__.py", line 1, in <mod
    from gmusicapi.clients.webclient import Webclient
  File "/volume1/public/gmusic-playlist/gmusicapi/clients/webclient.py", line 6, in <mo
    from gmusicapi.clients.shared import _Base
  File "/volume1/public/gmusic-playlist/gmusicapi/clients/shared.py", line 3, in <modul
    from gmusicapi.utils import utils
  File "/volume1/public/gmusic-playlist/gmusicapi/utils/utils.py", line 19, in <module>
    from google.protobuf.descriptor import FieldDescriptor
ImportError: No module named google.protobuf.descriptor
```

I have tried on Synolgy with pyton 2.7.11 and on Windows with pyton 2.7.10 and I have the same error.
It is a missing package ?

**Comment by soulfx** [comment]
yup protobuf would need to be installed.  just an fyi, the only python install i could get gmusicapi working on in windows was the python that comes with cygwin.

**Comment by Flavien06** [comment]
Ok, I discover python
It missed module (decorator, validictory)

```
Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "C:\Python27\gmusic-playlist\common.py", line 5, in <module>
    from gmusicapi import Mobileclient
  File "C:\Python27\lib\site-packages\gmusicapi-9.0.1.dev0-py2.7.egg\gmusicapi\__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "C:\Python27\lib\site-packages\gmusicapi-9.0.1.dev0-py2.7.egg\gmusicapi\clients\__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "C:\Python27\lib\site-packages\gmusicapi-9.0.1.dev0-py2.7.egg\gmusicapi\clients\webclient.py", line 13, in <module>
    import gmusicapi.session
  File "C:\Python27\lib\site-packages\gmusicapi-9.0.1.dev0-py2.7.egg\gmusicapi\session.py", line 12, in <module>
    import gpsoauth
  File "C:\Python27\lib\site-packages\gpsoauth-0.2.0-py2.7.egg\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth-0.2.0-py2.7.egg\gpsoauth\google.py", line 4, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey
```

I install pycrypto with "pip install pycrypto", but I still have the error. an idea?

**Comment by Flavien06** [comment]
For pyctypto : http://www.voidspace.org.uk/python/modules.shtml#pycrypto

Now it is work, I have install module : httplib2, mutagen, dateutil.
