### ISSUE TITLE
ImportError: Cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by edsonsouza92** [soulfx/gmusic-playlist#51]
tried to run ImportedList.py and get this:

```
Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/home/edson/Downloads/gmusic-playlist-master/common.py", line 9, in <module>
    from gmusicapi import __version__ as gmusicapi_version
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.1.1rc1-py2.7.egg/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.1.1rc1-py2.7.egg/gmusicapi/clients/__init__.py", line 4, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.1.1rc1-py2.7.egg/gmusicapi/clients/webclient.py", line 16, in <module>
    from gmusicapi.clients.shared import _Base
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.1.1rc1-py2.7.egg/gmusicapi/clients/shared.py", line 7, in <module>
    from gmusicapi.utils import utils
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-10.1.1rc1-py2.7.egg/gmusicapi/utils/utils.py", line 24, in <module>
    from google.protobuf.descriptor import FieldDescriptor
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.2.0rc1-py2.7.egg/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.12: cannot open shared object file: No such file or directory
```

**Comment by soulfx** [comment]
double check that the gmusicapi dependencies are getting installed correctly. 

in particular check the protobuf dependency.  try installing it via pip, some distros may have it available via their package management,  or building and installing it from source. 

after all the dependencies have been installed,  you should be able to run the scripts.  when running the playlist scripts you shouldn't need to use sudo
